### ISSUE TITLE
incorrect partial result when used with arrays

### ISSUE THREAD

**Issue by Tombre** [rook2pawn/node-partial#4]
I was giving your package a go when I found some unexpected behaviours when partially applying arrays to a function.  `partial` seems to apply the array as arguments of the function, as opposed to actually passing it as an argument.

Take this example:

```javascript
const partial = require('partial');

let fn = function(toLog, toLogSecond) {
	console.log(toLog);
	console.log(toLogSecond);
}

let partialApplication = partial(fn, ['log', 'this', 'array']);
partialApplication('done');

// will log: 
// -----------------------------------
// log
// this

// would have expected:
// -----------------------------------
// ['log', 'this', 'array']
// done
```

The fact that this example logs 'log' then 'this' indicates that you're applying the array as arguments instead of passing it through. Is that the intended result?

**Comment by rook2pawn** [comment]
@Tombre Definitely not, good catch. Fixing it tonight and commiting! Thanks!

**Comment by rook2pawn** [comment]
@Tombre 75acea44d0667070daf03fd1446def343f92bac1 committed
